version: "3"

services:
  elasticsearch-imap:
    depends_on:
      - elasticsearch
    build:
      context: .
      args:
        VERSION: 1.1-es2.3
    env_file: .env

  elasticsearch:
    image: elasticsearch:2
    ports:
      - 9200
      - 9300

  kibana:
    image: kibana:4.6
    ports:
      - 5601
